services:
  # Superset web service
  - type: web
    name: nfl-superset
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: standard
    healthCheckPath: /health
    envVars:
      - key: SUPERSET_SECRET_KEY
        generateValue: true
      - key: DATABASE_DIALECT
        value: postgresql
      - key: DATABASE_HOST
        value: aws-0-us-east-2.pooler.supabase.com
      - key: DATABASE_PORT
        # Make sure this is a string that can be converted to an integer
        value: 6543
      - key: DATABASE_DB
        value: postgres
      - key: DATABASE_USER
        value: postgres.rqyxyfqpudibodldwwqt
      - key: DATABASE_PASSWORD
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: REDIS_HOST
        fromService:
          name: nfl-superset-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: nfl-superset-redis
          type: redis
          property: port
      - key: SUPERSET_ENV
        value: production
      - key: PYTHONPATH
        value: /app/pythonpath
      - key: FLASK_APP
        value: superset.app:create_app()
      - key: FLASK_ENV
        value: production

  # Redis service for caching and celery
  - type: redis
    name: nfl-superset-redis
    ipAllowList: []